// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"
)

type Bid struct {
	ID        string    `json:"id"`
	Amount    float64   `json:"amount"`
	Bidder    string    `json:"bidder"`
	CreatedAt time.Time `json:"createdAt"`
}

type ChangedEstate struct {
	ID          string  `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type DeleteEstate struct {
	ID string `json:"id"`
}

type Estate struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	RegisteredAt   time.Time `json:"registeredAt"`
	OpenForBidTill time.Time `json:"openForBidTill"`
	Bids           []Bid     `json:"bids"`
}

type NewBid struct {
	EstateID string  `json:"estateID"`
	Amount   float64 `json:"amount"`
	Bidder   string  `json:"bidder"`
}

type NewEstate struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}
